--- 
title: '[Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression)'
author: '[Seth Harrison](https://username.github.io/)'
date: 'Last compiled: `r format(Sys.time(), "%b %d, %Y")`'
bibliography:
- book.bib
- packages.bib
description: This is starter code for using the bookdown package to write a book.
  The output format for this example is bookdown::gitbook.
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
always_allow_html: true
---

# Prerequisites

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", fig.width = 4, fig.height = 4)
library(tidyverse)
library(caret)
library(mlbench)
library(caTools)
library(openintro)
# Parallel Processing
library(doMC)
registerDoMC(cores = 12)
```

This material is from the [DataCamp](https://www.datacamp.com) course [Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) by Ben Baumer.  Before using this material, the reader should have completed and be comfortable with the material in the DataCamp modules [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r).


Reminder to self: each `*.Rmd` file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.




```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
